### ISSUE TITLE
Is there a way to plot 2d heatmap?

### ISSUE THREAD

**Issue by AtilaSaraiva** [kookma/ogpf#11]
From what I could understand from the code and README.md, the only way to plot sets of x,y,z points in a 2d raster would be with a contour plot. However, I am not that experience with the software, so I'd like to know if there is a way to do that.

**Comment by kookma** [comment]
See example 105! It shows a nice surface plot! It also uses contour+surface in one plot!
So, ogpf con do that!

**Comment by AtilaSaraiva** [comment]
Sorry, I didn't express myself correctly, I want to make a x,y,z plot without the contours. Just with the color variation.

**Comment by kookma** [comment]
> Sorry, I didn't express myself correctly, I want to make a x,y,z plot without the contours. Just with the color variation.

No problem, it is a surface plot! A heat map can be plotted using surf(x,y,z) if you need to use special color palette then call surf like `surf(x,y,z,palette)`
