### ISSUE TITLE
[gnuplot in windows 10] the command 'gnuplot -persist' will make the cpu fully loaded

### ISSUE THREAD

**Issue by zoziha** [kookma/ogpf#15]
Using `gnuplot -persist` under Windows10 will cause the following problems:
![image](https://user-images.githubusercontent.com/32035096/116858073-63efce00-ac30-11eb-9aa7-f4ce75f26bb5.png)

**The CPU occupancy is high**, which may be a Windows-gnuplot's bug. After testing, it is found that using the `wgnuplot -persist` command under Windows10 will not cause unexplained CPU occupancy problems.
![image](https://user-images.githubusercontent.com/32035096/116858123-7538da80-ac30-11eb-8a19-f7af03e97967.png)

**Comment by kookma** [comment]
@zoziha  thank you for your feedback!
If I correctly understand, your test shows gnuplot has high CPU usage comparing to wgnuplot!
and you proposed to use wgnuplot on Windows and keep execution on all other OS intact!

**Comment by kookma** [comment]
Thank you!
