### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ily83** [kookma/ogpf#20]
Hello,

Do you think it is possible to extend ogpf so that it can multiplot animation? Or is it limited by gnuplot or fortran arrays itself?

**Comment by kookma** [comment]
> ‘write(_,'(a, f5.3)') 'pause: ', pause' when pause is equal to 10.5 return "_***"

Testing on GNU Fortran 10.0

```fortran
program hello
    implicit none
    integer:: i
    real, dimension(:), allocatable :: x

    x = [1.40, 11.25, 35.8478, 99.99, 100.36 ]

    do i=1, 5
        write(*,'(a, f5.2)') 'pause: ', x(i)
    enddo

end program
```

produces:

```text
pause:  1.40
pause: 11.25
pause: 35.85
pause: 99.99
pause: *****

Process returned 0 (0x0)   execution time : 0.016 s
Press any key to continue.
```

I just think to use some meaningful value and format!

**Comment by Ily83** [comment]
I changed it to F5.2
