### ISSUE TITLE
Is it possible to add options after calling a plot subroutine?

### ISSUE THREAD

**Issue by macardosa** [kookma/ogpf#27]
I'm unable to see the plots with wxt term in macOS because Gnuplot exist and the window close very fast. 

Using persistent:
```
gnuplot -p ogpf_temp_script.gp
```
does not work.
I managed to see the plot by adding **pause mouse close** or **pause -1** to the end of the script.
I wonder if it is possible to set this option from the Fortran program.

Thanks in advance

Best
Manuel

**Comment by kookma** [comment]
Note: when you plot something after that, you cannot pipe anything!
Actually Fortran send all data to a text file and gnuplot reads it!
