### ISSUE TITLE
Is that possible to use that in Visual Studio IDE using intel compiler?

### ISSUE THREAD

**Issue by maiwending** [kookma/ogpf#34]
Very cool functionality.

I have tried FPM. It works.
But usually I use Visual Studio for easy debugging. Is that possible to be integrated with VS and how?

Thanks,

**Comment by kookma** [comment]
If you use Visual Studio for Fortran Projects, then it should be easy!

NOTE: There is no dependency! ogpf is a signle fortran file, just copy it in the same project folder and use it!
Or you can have a library folder and from VS add the ogpf.f90 to your project!

In summary: no installation is required!

**Comment by maiwending** [comment]
It works perfectly. Thank you very much!
