### ISSUE TITLE
The documentation websit elink is broken.

### ISSUE THREAD

**Issue by shahmoradi** [kookma/ogpf#35]
https://kookma.github.com/ogpf is broken. Has the site moved to another address?

**Comment by fccf** [comment]
This is an automatic reply, confirming that your e-mail was received.Thank you!

**Comment by kookma** [comment]
Hi Amir (@shahmoradi)
Actually all explanations and examples were moved to Readme.md. Sorry for inconvenience, I deleted the wrong link!
