### ISSUE TITLE
Failing Examples 

### ISSUE THREAD

**Issue by general-rishkin** [kookma/ogpf#37]
All the plots that have multiple plots on them, e.g., example 9: 

```
  call gp%plot(x(1:i),y(1:i), 'w lines lc "red" lw 2', &
      x(i:i), y(i:i),'w points ps 3 pt 7 lc "red"', &
      x(1:i),z(1:i), 'w lines lc "blue" lw 2', &
      x(i:i), z(i:i), 'w points ps 3 pt 7 lc "blue"' )
```
 fail with the following error:

> 
>  27 |             call gp%plot(x(1:i),y(1:i), 'w lines lc "red" lw 2', &
>       |                   1
> Error: Found no matching specific binding for the call to the GENERIC ‘plot’ at (1)
> <ERROR> Compilation failed for object " app_plot_ogpf.f90.o "

I am using `fpm` with gfortran 11.2.

**Comment by fccf** [comment]
This is an automatic reply, confirming that your e-mail was received.Thank you!

**Comment by kookma** [comment]
I cannot reproduce this error on gfortran 10.3 and gnuplot 5.4 (Windows 10).
I have not gfortran 11.2 but I do think ogpf works well with gfortran 11

**Comment by general-rishkin** [comment]
This is the full 
```
program plot_ogpf
  use ogpf
  implicit none
  call exmp09()

contains

  subroutine exmp09
    type(gpf):: gp
        integer, parameter::   n  = 35
        real(wp), parameter :: pi = 4.d0*atan(1.d0)
        real(wp):: x(n)
        real(wp):: y(n), z(n)
        integer :: i

        x=linspace(-pi, pi,n)
        y = 0.0_wp
        z = 0.0_wp
        call gp%animation_start(1.0) ! start animation, set delay is one second between frames
        call gp%axis([-pi, pi, -1.2_wp, 1.2_wp])
        call gp%options('set grid')
        ! add frames
        do i=1, n, 10
            y(i) = sin(x(i))
            z(i) = cos(x(i))
            ! each plot command adds one frame
            call gp%plot(x(1:i),y(1:i), 'w lines lc "red" lw 2', &
                x(i:i), y(i:i),'w points ps 3 pt 7 lc "red"', &
                x(1:i),z(1:i), 'w lines lc "blue" lw 2', &
                x(i:i), z(i:i), 'w points ps 3 pt 7 lc "blue"' )
        end do
        ! finalize and show frames one by one with delay between them
        ! as set by animation_start
        call gp%animation_show()
  end subroutine exmp09
end program plot_ogpf
```

and this is my fpm.toml:

```
name = "ogpf_test"
version = "0.1.0"
license = "license"
author = "Jane Doe"
maintainer = "jane.doe@example.com"
copyright = "Copyright 2022, Jane Doe"

auto-executables = false #true
auto-tests = true
auto-examples = true

[install]
library = false

[dependencies]
ogpf = { git = "https://github.com/kookma/ogpf.git" }

[[ executable ]]
name="ogpf_plot_test"
source-dir="app"
main="plot_ogpf.f90"
```

**Comment by 14NGiestas** [comment]
I can't confirm the issue with `gfortran`  using `11.2`.
I believe it could be your environment (since nvfortran and others can mess badly with it), try passing a specific compiler to fpm, like:
```sh
fpm build --compiler gfortran
```
Just make sure to do `gfortran -v` to confirm the version

PS: I'm trying to compile using nvfortran but my environment seems to be messed up as well (I need to figure out the linker flags). I'm doing the following:
```sh
fpm build --compiler nvfortran --flag Mbackslash
```
The `-Mbackslash` here is needed since `nvfortran` treats `\'` as a string escaping in my env (It's probably non-standard ).

**Comment by 14NGiestas** [comment]
I managed to compile with `nvfortran` ( I just had to `sudo ln -s 11.2.0 10.2.0` inside `/usr/lib/gcc/x86_64-pc-linux-gnu/` to temporally fix an issue with my linker)
```sh
fpm build --compiler nvfortran --flag "-Mbackslash"
```
Here is the compiler I'm using
```sh
$ nvfortran --version
nvfortran 21.1-0 LLVM 64-bit target on x86-64 Linux -tp haswell 
NVIDIA Compilers and Tools
Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
```

**Comment by ax-hack** [comment]
Hi, I've got same error at example 6

Error text

> 29 |         call gplot%plot(x,y,'title "sin(x)" with lines lt 2 lw 3', &
      |                  1
Error: Found no matching specific binding for the call to the GENERIC ‘plot’ at (1)
<ERROR> Compilation failed for object " src_FSABotHelperTwo.f90.o "

gfortran --version

> gfortran --version                                                                                                         10/04/2023 06:46:45 PM
GNU Fortran (Gentoo Hardened 13.2.1_p20230826 p7) 13.2.1 20230826
Copyright (C) 2023 Free Software Foundation, Inc.

gnuplot 5.4.8
