### ISSUE TITLE
Possibility of using custom palette

### ISSUE THREAD

**Issue by huijunchen9260** [kookma/ogpf#42]
Hi there! I am wondering is it possible to use custom palette if I store the .pal file from the [gnuplot-palettes](https://github.com/Gnuplotting/gnuplot-palettes) in some path?

Thank you for this wonderful project!

**Comment by 14NGiestas** [comment]
Hi, try using the options feature and the commands suggested by the link you gave, separated by ";".

```f90
call GP % options("load pallet.pal; ...")
```
If it doesn't work please attach the temporary/output script and relevant files.

FWIW I was working on this [patch](https://github.com/kookma/ogpf/compare/master...14NGiestas:ogpf:patch-3) but I had to stop, so it may be a missing feature.

**Comment by huijunchen9260** [comment]
Hi @14NGiestas , thank you so much for your suggestion! Yet somehow I still not able to let it work. The attachment is a zip file contains two files: the one called "fail" means that I use `gp%options("load 'jet.pal'")` and is not working, and the other one means that I use the `palette` to define the color.

Thank you again for your support!

[loadJetpal.zip](https://github.com/kookma/ogpf/files/9778490/loadJetpal.zip)

**Comment by 14NGiestas** [comment]
Sure, remember that ogpf is just a tool to write a gnuplot script and call it automatically.

Any errors in the terminal? Like a missing path?

As per [gnuplotting](
http://www.gnuplotting.org/ease-your-plotting-with-config-snippets/) maybe it helps using the set loadpath command with an absolute/some path to your config folder.

The load command will basically include it's contents in the file, and it's contents it's pretty much what the palette (in fortran) outputs (as you can see at the beginning of the scripts you gave me).

I'm not sure but just in case: append an `set style data lines;` to your options command, after you loaded the pal file.

Also be sure that your pal file is compatible with the data you are trying to show (Ex. Defining line colors but plotting no lines).

PS: I am away from a computer rn, so I am unable to test it, always refer to the gnuplot docs when in doubt.

**Comment by huijunchen9260** [comment]
Hi all:

I indeed want to use ogpf and gnuplot, but now I am switched to pyplot-fortran due to the simplicity that matplotlib is providing...so I will just close this issue to stop bothering you guys for my own lack of knowledge of gnuplot.

Thanks!

HJ

**Comment by 14NGiestas** [comment]
@huijunchen9260 good to hear you are solving your issues with other tool, but keep "bothering" here so it can improve :) gnuplot is kinda hard and messy to use directly. ogpf is a good way to simplify a lot of the plot handling in Fortran, though it's far from a complete experience. 

So nothing we tried here did work, it seems stills an issue to me.

**Comment by huijunchen9260** [comment]
That's true. Nothing here can change the custom palette other than the predetermined palette that is described in README.md.

To me the 3D plotting in gnuplot is fast to get the large dimensional data done but slow in terms of interaction with the 3D plotting, like the rotating of the 3D plot is extremely slow for me in wxt terminal. (My array is like 1000 x 1000)

To be honest I don't know. I don't know which way is better, and I guess I need to try more if I want this project to be improved, but matplotlib just gets the job done in a seamless way, like latex axis label and the legend position. I don't know what kind of magic that matplotlib is doing, but somehow after using that I don't need to specify the legend position anymore. I do notice that gnuplot is indeed faster in terms of reading those 1000x1000 array. I guess that's the benefit of gnuplot.

**Comment by 14NGiestas** [comment]
To be honest, I don't know. The gnuplot rendering isn't the best for interactive 3D plots anyway, maybe with a proper 3D viewer/render.
Try just under-sampling your data before plotting.

[openGL support to gnuplot discussion, which could improve things, but isn't so easy to implement](https://sourceforge.net/p/gnuplot/mailman/gnuplot-beta/thread/201008231335.08576.merritt%40u.washington.edu/).
