### ISSUE TITLE
bug fix (kind specification and so on)

### ISSUE THREAD

**Issue by sakamoti** [kookma/ogpf#7]
I'm very happy to find the tool which enable me to use gnuplot from fortran. Thank you for your great job.

I sometimes use the compiler other than gfortran. When I tried to compile this project with that compiler, I encounter some problems like below. 

- "kind parameter is not defined" : default kind specification system is different between compilers, if kind specification is given by number directly, compilation failed without "non-default" settings.

- "segmentation fault occured": When not allocated character object is used in the "len_trim" function, sometimes segmentation fault occures.

- "error from gnuplot in example 108": Demo program (Example 108) cause error from gnuplot because line color is blank.

May I send pull request?

**Comment by kookma** [comment]
@sakamoti 
Many thanks for submitting bugs! Well please send a PR! By the way we need to keep ogpf backward compatible!

**Comment by sakamoti** [comment]
Closing this issue since the related Pull Request was merged.
