### ISSUE TITLE
ENH: improve set_axis interface to allow set individual axis range

### ISSUE THREAD

**Issue by 14NGiestas** [kookma/ogpf#9]
The function interface doesn't allow to set one specific range like `yrange` or `zrange` without having to set the `xrange`
I suggest using optional arguments to set each individual argument and/or maybe writing 3 new methods to each one.
EDIT: However would be nice to keep the old interface, so maybe this would be a extension
```fortran
type, public :: gpf
    private
    (...)
contains
    (...)
    procedure, pass, public :: axis  => set_axis_matlab, set_axis_individuals
end type
(...)
subroutine set_axis_matlab(this, range_array)
       (...) original implementation
end subroutine
(...)
subroutine set_axis_individuals(this, xrange, yrange, zrange)
       class(gpf):: this
       real(wp), optional, intent(in) :: xrange(2)
       real(wp), optional, intent(in) :: yrange(2)
       real(wp), optioanl, intent(in) :: zrange(2)
       if (present(xrange)) then
               this%hasxrange=.true.
               this%xrange=xrange
       end if
       if (present(yrange)) then
               this%hasyrange=.true.
               this%yrange=yrange
       end if
       if (present(zrange)) then
               this%haszrange=.true.
               this%zrange=zrange
       end if
end subroutine
```
PS "forking" the issue from #5 to a specific one

**Comment by kookma** [comment]
I think it is better to have the current routine as is and add another routines to set xlim ylim, zlim separately! The ogpf closely follow the syntax in Octave and Matlab. This is only for simplicity.

See 

- https://octave.org/doc/v5.2.0/Axis-Configuration.html
- https://octave.org/doc/v5.2.0/Axis-Configuration.html#XREFxlim
- https://octave.org/doc/v5.2.0/Axis-Configuration.html#XREFylim
- https://octave.org/doc/v5.2.0/Axis-Configuration.html#XREFzlim
- http://www.ece.northwestern.edu/local-apps/matlabhelp/techdoc/ref/ylim.html

**Comment by 14NGiestas** [comment]
> I think it is better to have the current routine as is and add another routines to set xlim ylim, zlim separately! The ogpf closely follows the syntax in Octave and Matlab. This is only for simplicity.
> 
> See
> 
> * https://octave.org/doc/v5.2.0/Axis-Configuration.html
> * https://octave.org/doc/v5.2.0/Axis-Configuration.html#XREFxlim
> * https://octave.org/doc/v5.2.0/Axis-Configuration.html#XREFylim
> * https://octave.org/doc/v5.2.0/Axis-Configuration.html#XREFzlim
> * http://www.ece.northwestern.edu/local-apps/matlabhelp/techdoc/ref/ylim.html

That could work too, I gonna check the links you sent to see their interfaces and propose another pull request addressing this issue.
